import React from 'react';
import { Link } from 'react-router-dom';

const FEATURES = [
  { id: '01', title: 'Synthetic Data Augmentation', body: 'Five synthetic manipulations (blend/warp, frequency perturbation, compression artifacts, colour perturbation and autoencoder swaps) are used to train the face model in an augmentation study that is tested on a manipulation method never seen in training.', span: 4 },
  { id: '02', title: 'Face-Manipulation Detector', body: 'When a face is found, a CLIP ViT-L/14 model checks it for face swaps and reenactment.', span: 8 },
  { id: '03', title: 'AI-Image Detector', body: 'A Community Forensics Vision Transformer checks the whole image for signs that it was fully generated by AI.', span: 6 },
  { id: '04', title: 'Explainable Verdict', body: 'A multi-factor engine combines ML detector scores with measured eye, nose/mouth, skin, boundary, lighting, background and frequency signals into REAL and FAKE scores, and returns REAL, AI-GENERATED, DEEPFAKE or UNCERTAIN with the reason.', span: 6 },
  { id: '05', title: 'Provenance Evidence', body: 'EXIF, XMP and IPTC metadata and C2PA manifests are read as supporting evidence; missing metadata never counts as proof of a fake.', span: 12 },
];

export default function FeaturesPage() {
  return (
    <div className="features-page">
      <header className="features__header">
        <p className="features__kicker">Capabilities</p>
        <h1 className="features__title">Detection <span>Signals</span></h1>
        <p className="features__subtitle">
          DeepScan uses two detection models, one trained with synthetic data augmentation,
          plus metadata and provenance checks, to explain whether media is real or manipulated.
        </p>
      </header>

      <div className="features-grid">
        {FEATURES.map((f) => (
          <div key={f.id} className={`fcard fcard--span${f.span}`}>
            <div className="fcard__header">
              <span className="fcard__num">{f.id}</span>
              <span className="fcard__tag">Module</span>
            </div>
            <h2 className="fcard__title">{f.title}</h2>
            <p className="fcard__body">{f.body}</p>
          </div>
        ))}
      </div>

      <div className="features__footer">
        <Link to="/checker" className="features__btn features__btn--primary">Get started</Link>
        <Link to="/how-it-works" className="features__btn features__btn--secondary">How it works</Link>
      </div>
    </div>
  );
}
